import React, { useState, useEffect, useCallback } from 'react';
import { View, Text, StyleSheet, FlatList, TouchableOpacity, Alert, ScrollView } from 'react-native';
import { FileText, Eye, Calendar, DollarSign, Send, RefreshCw, Clock } from 'lucide-react-native';
import { useApp } from '@/contexts/AppContext';
import { Invoice } from '@/types';
import { generateInvoiceNumber, generateInvoiceData, generateMonthlyInvoiceDate, shouldGenerateInvoice, shareInvoicePDF } from '@/utils/invoiceGenerator';
import { 
  getSchedulesReadyForGeneration, 
  shouldGenerateScheduledInvoice, 
  generateScheduledInvoice, 
  getUpcomingScheduledInvoices 
} from '@/utils/invoiceScheduler';
import { getCurrencySymbol, DEFAULT_CURRENCY } from '@/constants/currencies';
import Button from '@/components/Button';
import Card from '@/components/Card';
import Modal from '@/components/Modal';
import Badge from '@/components/Badge';
import EmptyState from '@/components/EmptyState';
import SwipeableItem, { SwipeAction } from '@/components/SwipeableItem';

export default function InvoicesScreen() {
  const { 
    invoices, 
    addInvoice, 
    updateInvoice, 
    leases, 
    tenantRenters, 
    properties, 
    units,
    currentTenant,
    businessLogo,
    invoiceSchedules,
    updateInvoiceSchedule,
  } = useApp();
  
  const [detailModalVisible, setDetailModalVisible] = useState<boolean>(false);
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);

  useEffect(() => {
    console.log(`[Invoices] Loaded ${invoices.length} invoices, ${invoiceSchedules.length} schedules`);
  }, [invoices.length, invoiceSchedules.length]);

  useEffect(() => {
    const processScheduledInvoices = async () => {
      const readySchedules = getSchedulesReadyForGeneration(invoiceSchedules, invoices);
      
      if (readySchedules.length > 0) {
        console.log(`[INVOICE_SCHEDULER] Found ${readySchedules.length} schedules ready for invoice generation`);
        
        for (const schedule of readySchedules) {
          const lease = leases.find(l => l.id === schedule.lease_id);
          const tenantRenter = tenantRenters.find(tr => tr.id === schedule.tenant_renter_id);
          const property = properties.find(p => p.id === schedule.property_id);
          const unit = units.find(u => u.id === schedule.unit_id);
          
          if (lease && tenantRenter && property && unit) {
            const invoiceData = generateScheduledInvoice({
              schedule,
              lease,
              tenantRenter,
              property,
              unit,
              existingInvoicesCount: invoices.length,
            });
            
            await addInvoice(invoiceData);
            
            const checkResult = shouldGenerateScheduledInvoice(schedule, invoices);
            await updateInvoiceSchedule(schedule.id, {
              last_generation_date: new Date().toISOString().split('T')[0],
              next_generation_date: checkResult.nextGenerationDate,
            });
            
            console.log(`[INVOICE_SCHEDULER] Generated invoice ${invoiceData.invoice_number} for schedule ${schedule.id}`);
          }
        }
      }
    };
    
    processScheduledInvoices();
  }, [invoiceSchedules, invoices, leases, tenantRenters, properties, units, addInvoice, updateInvoiceSchedule]);

  const handleAutoGenerateInvoices = useCallback(async () => {
    setIsGenerating(true);
    console.log('[Invoices] Starting auto-generation for active leases');
    
    try {
      const activeLeases = leases.filter(l => l.status === 'active');
      console.log(`[Invoices] Found ${activeLeases.length} active leases`);
      
      let generatedCount = 0;
      
      for (const lease of activeLeases) {
        if (shouldGenerateInvoice(lease, invoices)) {
          const tenantRenter = tenantRenters.find(tr => tr.id === lease.tenant_renter_id);
          const property = properties.find(p => p.id === lease.property_id);
          const unit = units.find(u => u.id === lease.unit_id);
          
          if (tenantRenter && property && unit) {
            const { invoiceDate, dueDate } = generateMonthlyInvoiceDate(lease);
            const invoiceNumber = generateInvoiceNumber(invoices.length + generatedCount);
            
            const invoiceData = generateInvoiceData({
              lease,
              tenantRenter,
              property,
              unit,
              invoiceDate,
              dueDate,
              currency: DEFAULT_CURRENCY,
              invoiceNumber,
              autoGenerated: true,
              recurringPeriod: 'monthly',
              notes: `Monthly rent invoice for ${property.name}, Unit ${unit.unit_number}`,
            });
            
            await addInvoice(invoiceData);
            generatedCount++;
            console.log(`[Invoices] Generated invoice ${invoiceNumber} for ${tenantRenter.email}`);
          }
        }
      }
      
      if (generatedCount > 0) {
        Alert.alert('Success', `Generated ${generatedCount} invoice${generatedCount > 1 ? 's' : ''} successfully!`);
      } else {
        Alert.alert('Info', 'No new invoices to generate. All active leases have invoices for this period.');
      }
    } catch (error) {
      console.error('[Invoices] Error during auto-generation:', error);
      Alert.alert('Error', 'Failed to generate invoices. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  }, [leases, tenantRenters, properties, units, invoices, addInvoice]);

  const handleViewInvoice = (invoice: Invoice) => {
    setSelectedInvoice(invoice);
    setDetailModalVisible(true);
  };

  const handleShareInvoice = async (invoice: Invoice) => {
    const tenantRenter = tenantRenters.find(tr => tr.id === invoice.tenant_renter_id);
    const property = properties.find(p => p.id === invoice.property_id);
    const unit = units.find(u => u.id === invoice.unit_id);
    
    if (!tenantRenter || !property || !unit) {
      Alert.alert('Error', 'Unable to find invoice details');
      return;
    }

    const landlordInfo = {
      name: currentTenant?.name || 'Landlord',
      address: property.address,
      email: currentTenant?.email || '',
      phone: currentTenant?.phone || '',
      logo: businessLogo,
    };

    try {
      console.log('[Invoices] Starting PDF generation and share for invoice', invoice.invoice_number);
      await shareInvoicePDF(invoice, tenantRenter, property, unit, landlordInfo);
      
      await updateInvoice(invoice.id, { 
        sent_at: new Date().toISOString(),
        status: 'sent'
      });
      
      Alert.alert('Success', `Invoice ${invoice.invoice_number} PDF shared successfully!`);
    } catch (error) {
      console.error('[Invoices] Error sharing PDF:', error);
      Alert.alert('Error', 'Failed to share invoice PDF. Please try again.');
    }
  };



  const handleMarkAsPaid = async (invoice: Invoice) => {
    Alert.alert(
      'Mark as Paid',
      `Confirm that invoice ${invoice.invoice_number} has been paid?`,
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Confirm', 
          style: 'default',
          onPress: async () => {
            await updateInvoice(invoice.id, { 
              status: 'paid',
              paid_at: new Date().toISOString(),
              amount_paid: invoice.total_amount,
              balance_due: 0,
            });
            Alert.alert('Success', 'Invoice marked as paid');
            setDetailModalVisible(false);
          }
        },
      ]
    );
  };

  const getStatusVariant = (status: string): 'success' | 'warning' | 'danger' | 'info' | 'default' => {
    switch (status) {
      case 'paid':
        return 'success';
      case 'sent':
        return 'info';
      case 'overdue':
        return 'danger';
      case 'draft':
        return 'default';
      case 'cancelled':
        return 'default';
      default:
        return 'default';
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const renderInvoice = ({ item }: { item: Invoice }) => {
    const tenantRenter = tenantRenters.find(tr => tr.id === item.tenant_renter_id);
    const property = properties.find(p => p.id === item.property_id);
    const unit = units.find(u => u.id === item.unit_id);
    const currencySymbol = getCurrencySymbol(item.currency);
    
    const tenantName = tenantRenter 
      ? (tenantRenter.type === 'business' ? tenantRenter.business_name : `${tenantRenter.first_name} ${tenantRenter.last_name}`)
      : 'Unknown';

    const swipeActions: SwipeAction[] = [
      {
        text: 'View',
        backgroundColor: '#007AFF',
        color: '#FFFFFF',
        icon: <Eye size={20} color="#FFFFFF" />,
        onPress: () => handleViewInvoice(item),
        testID: `swipe-view-invoice-${item.id}`,
      },
      {
        text: 'Share',
        backgroundColor: '#34C759',
        color: '#FFFFFF',
        icon: <Send size={20} color="#FFFFFF" />,
        onPress: () => handleShareInvoice(item),
        testID: `swipe-share-invoice-${item.id}`,
      },
    ];

    if (item.status !== 'paid') {
      swipeActions.push({
        text: 'Mark Paid',
        backgroundColor: '#FF9500',
        color: '#FFFFFF',
        icon: <DollarSign size={20} color="#FFFFFF" />,
        onPress: () => handleMarkAsPaid(item),
        testID: `swipe-paid-invoice-${item.id}`,
      });
    }

    return (
      <SwipeableItem rightActions={swipeActions} testID={`swipeable-invoice-${item.id}`}>
        <Card style={[styles.invoiceCard, item.status === 'overdue' && styles.overdueCard]}>
        <TouchableOpacity onPress={() => handleViewInvoice(item)}>
          <View style={styles.invoiceHeader}>
            <View style={styles.invoiceInfo}>
              <View style={styles.invoiceNumberRow}>
                <FileText size={18} color="#007AFF" />
                <Text style={styles.invoiceNumber}>{item.invoice_number}</Text>
                {item.auto_generated && (
                  <View style={styles.autoTag}>
                    <RefreshCw size={10} color="#666" />
                    <Text style={styles.autoTagText}>Auto</Text>
                  </View>
                )}
              </View>
              <Text style={styles.tenantName}>{tenantName}</Text>
              <Text style={styles.propertyInfo}>
                {property?.name} - Unit {unit?.unit_number}
              </Text>
            </View>
            <View style={styles.invoiceAmount}>
              <Text style={styles.amount}>
                {currencySymbol}{item.total_amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </Text>
              <Text style={styles.currency}>{item.currency}</Text>
              <Badge label={item.status} variant={getStatusVariant(item.status)} />
            </View>
          </View>

          <View style={styles.datesRow}>
            <View style={styles.dateItem}>
              <Calendar size={14} color="#666" />
              <Text style={styles.dateLabel}>Issued:</Text>
              <Text style={styles.dateText}>{formatDate(item.invoice_date)}</Text>
            </View>
            <View style={styles.dateItem}>
              <Calendar size={14} color={item.status === 'overdue' ? '#FF3B30' : '#666'} />
              <Text style={styles.dateLabel}>Due:</Text>
              <Text style={[styles.dateText, item.status === 'overdue' && { color: '#FF3B30', fontWeight: '700' }]}>
                {formatDate(item.due_date)}
              </Text>
            </View>
          </View>
        </TouchableOpacity>

        <View style={styles.invoiceActions}>
          <TouchableOpacity
            style={styles.actionButton}
            onPress={() => handleViewInvoice(item)}
            testID={`view-invoice-${item.id}`}
          >
            <Eye size={16} color="#007AFF" />
            <Text style={styles.actionText}>View</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.actionButton}
            onPress={() => handleShareInvoice(item)}
            testID={`share-invoice-${item.id}`}
          >
            <Send size={16} color="#34C759" />
            <Text style={[styles.actionText, { color: '#34C759' }]}>Share</Text>
          </TouchableOpacity>
          {item.status !== 'paid' && (
            <TouchableOpacity
              style={styles.actionButton}
              onPress={() => handleMarkAsPaid(item)}
              testID={`mark-paid-invoice-${item.id}`}
            >
              <DollarSign size={16} color="#FF9500" />
              <Text style={[styles.actionText, { color: '#FF9500' }]}>Mark Paid</Text>
            </TouchableOpacity>
          )}
        </View>
        </Card>
      </SwipeableItem>
    );
  };

  const upcomingScheduled = getUpcomingScheduledInvoices(invoiceSchedules, 30);

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <View>
          <Text style={styles.headerTitle}>Invoices ({invoices.length})</Text>
          <Text style={styles.headerSubtitle}>
            {invoices.filter(i => i.status === 'paid').length} paid • {invoices.filter(i => i.status === 'overdue').length} overdue
          </Text>
          {upcomingScheduled.length > 0 && (
            <View style={styles.scheduledInfo}>
              <Clock size={12} color="#007AFF" />
              <Text style={styles.scheduledText}>
                {upcomingScheduled.length} scheduled in next 30 days
              </Text>
            </View>
          )}
        </View>
        <View style={styles.headerActions}>
          <TouchableOpacity
            style={[styles.autoGenButton, isGenerating && styles.autoGenButtonDisabled]}
            onPress={handleAutoGenerateInvoices}
            disabled={isGenerating}
            testID="auto-generate-invoices-button"
          >
            <RefreshCw size={20} color="#FFFFFF" />
            <Text style={styles.autoGenText}>{isGenerating ? 'Generating...' : 'Auto-Generate'}</Text>
          </TouchableOpacity>
        </View>
      </View>

      {invoices.length === 0 ? (
        <EmptyState
          icon={FileText}
          title="No Invoices"
          message="Auto-generate monthly invoices for your active leases"
          actionLabel="Auto-Generate Invoices"
          onAction={handleAutoGenerateInvoices}
          testID="invoices-empty"
        />
      ) : (
        <FlatList
          data={invoices.sort((a, b) => new Date(b.invoice_date).getTime() - new Date(a.invoice_date).getTime())}
          renderItem={renderInvoice}
          keyExtractor={item => item.id}
          contentContainerStyle={styles.list}
          showsVerticalScrollIndicator={false}
        />
      )}

      {selectedInvoice && (
        <InvoiceDetailModal
          visible={detailModalVisible}
          onClose={() => {
            setDetailModalVisible(false);
            setSelectedInvoice(null);
          }}
          invoice={selectedInvoice}
          tenantRenters={tenantRenters}
          properties={properties}
          units={units}
          onShare={handleShareInvoice}
          onMarkAsPaid={handleMarkAsPaid}
          currentTenant={currentTenant}
        />
      )}
    </View>
  );
}

interface InvoiceDetailModalProps {
  visible: boolean;
  onClose: () => void;
  invoice: Invoice;
  tenantRenters: any[];
  properties: any[];
  units: any[];
  onShare: (invoice: Invoice) => void;
  onMarkAsPaid: (invoice: Invoice) => void;
  currentTenant: any;
}

function InvoiceDetailModal({
  visible,
  onClose,
  invoice,
  tenantRenters,
  properties,
  units,
  onShare,
  onMarkAsPaid,
  currentTenant,
}: InvoiceDetailModalProps) {
  const tenantRenter = tenantRenters.find(tr => tr.id === invoice.tenant_renter_id);
  const property = properties.find(p => p.id === invoice.property_id);
  const unit = units.find(u => u.id === invoice.unit_id);
  const currencySymbol = getCurrencySymbol(invoice.currency);

  const tenantName = tenantRenter 
    ? (tenantRenter.type === 'business' ? tenantRenter.business_name : `${tenantRenter.first_name} ${tenantRenter.last_name}`)
    : 'Unknown';

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  };

  const getStatusVariant = (status: string): 'success' | 'warning' | 'danger' | 'info' | 'default' => {
    switch (status) {
      case 'paid': return 'success';
      case 'sent': return 'info';
      case 'overdue': return 'danger';
      case 'draft': return 'default';
      case 'cancelled': return 'default';
      default: return 'default';
    }
  };

  return (
    <Modal
      visible={visible}
      onClose={onClose}
      title={`Invoice ${invoice.invoice_number}`}
      testID="invoice-detail-modal"
    >
      <ScrollView style={styles.detailScroll} showsVerticalScrollIndicator={false}>
        <View style={styles.detailHeader}>
          <View style={styles.detailHeaderLeft}>
            <Text style={styles.detailInvoiceNumber}>{invoice.invoice_number}</Text>
            <Badge label={invoice.status} variant={getStatusVariant(invoice.status)} />
          </View>
          <View style={styles.detailHeaderRight}>
            <Text style={styles.detailAmount}>
              {currencySymbol}{invoice.total_amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </Text>
            <Text style={styles.detailCurrency}>{invoice.currency}</Text>
          </View>
        </View>

        <View style={styles.detailSection}>
          <Text style={styles.detailSectionTitle}>Bill To</Text>
          <Text style={styles.detailSectionValue}>{tenantName}</Text>
          <Text style={styles.detailSectionSub}>{tenantRenter?.email}</Text>
          <Text style={styles.detailSectionSub}>{tenantRenter?.phone}</Text>
        </View>

        <View style={styles.detailSection}>
          <Text style={styles.detailSectionTitle}>Property Details</Text>
          <Text style={styles.detailSectionValue}>{property?.name}</Text>
          <Text style={styles.detailSectionSub}>Unit {unit?.unit_number}</Text>
          <Text style={styles.detailSectionSub}>{property?.address}</Text>
        </View>

        <View style={styles.detailSection}>
          <Text style={styles.detailSectionTitle}>Dates</Text>
          <View style={styles.detailDatesRow}>
            <View style={styles.detailDateItem}>
              <Text style={styles.detailDateLabel}>Invoice Date</Text>
              <Text style={styles.detailDateValue}>{formatDate(invoice.invoice_date)}</Text>
            </View>
            <View style={styles.detailDateItem}>
              <Text style={styles.detailDateLabel}>Due Date</Text>
              <Text style={[styles.detailDateValue, invoice.status === 'overdue' && { color: '#FF3B30' }]}>
                {formatDate(invoice.due_date)}
              </Text>
            </View>
          </View>
        </View>

        <View style={styles.detailSection}>
          <Text style={styles.detailSectionTitle}>Line Items</Text>
          {invoice.line_items.map((item) => (
            <View key={item.id} style={styles.lineItemRow}>
              <View style={styles.lineItemLeft}>
                <Text style={styles.lineItemDescription}>{item.description}</Text>
                <Text style={styles.lineItemDetails}>
                  {item.quantity} × {currencySymbol}{item.unit_price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </Text>
              </View>
              <Text style={styles.lineItemAmount}>
                {currencySymbol}{item.amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </Text>
            </View>
          ))}
        </View>

        <View style={styles.detailTotals}>
          <View style={styles.detailTotalRow}>
            <Text style={styles.detailTotalLabel}>Subtotal:</Text>
            <Text style={styles.detailTotalValue}>
              {currencySymbol}{invoice.subtotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </Text>
          </View>
          {invoice.tax_amount && invoice.tax_amount > 0 && (
            <View style={styles.detailTotalRow}>
              <Text style={styles.detailTotalLabel}>Tax:</Text>
              <Text style={styles.detailTotalValue}>
                {currencySymbol}{invoice.tax_amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </Text>
            </View>
          )}
          {invoice.late_fee_amount && invoice.late_fee_amount > 0 && (
            <View style={styles.detailTotalRow}>
              <Text style={[styles.detailTotalLabel, { color: '#FF9500' }]}>Late Fee:</Text>
              <Text style={[styles.detailTotalValue, { color: '#FF9500' }]}>
                {currencySymbol}{invoice.late_fee_amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </Text>
            </View>
          )}
          <View style={[styles.detailTotalRow, styles.detailTotalRowFinal]}>
            <Text style={styles.detailTotalLabelFinal}>Total Amount:</Text>
            <Text style={styles.detailTotalValueFinal}>
              {currencySymbol}{invoice.total_amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} {invoice.currency}
            </Text>
          </View>
        </View>

        {invoice.notes && (
          <View style={styles.detailSection}>
            <Text style={styles.detailSectionTitle}>Notes</Text>
            <Text style={styles.detailNotes}>{invoice.notes}</Text>
          </View>
        )}

        <View style={styles.detailActions}>
          <Button
            title="Share Invoice"
            onPress={() => {
              onClose();
              onShare(invoice);
            }}
            icon={<Send size={18} color="#FFFFFF" />}
            fullWidth
            testID="detail-share-button"
          />
          {invoice.status !== 'paid' && (
            <Button
              title="Mark as Paid"
              onPress={() => onMarkAsPaid(invoice)}
              icon={<DollarSign size={18} color="#FFFFFF" />}
              fullWidth
              variant="secondary"
              testID="detail-mark-paid-button"
            />
          )}
        </View>

        <View style={{ height: 20 }} />
      </ScrollView>
    </Modal>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700' as const,
    color: '#1A1A1A',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  headerActions: {
    flexDirection: 'row' as const,
    gap: 8,
  },
  autoGenButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: '#007AFF',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
  },
  autoGenButtonDisabled: {
    backgroundColor: '#999',
  },
  autoGenText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600' as const,
  },
  list: {
    padding: 16,
  },
  invoiceCard: {
    marginBottom: 16,
  },
  overdueCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#FF3B30',
  },
  invoiceHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    marginBottom: 12,
  },
  invoiceInfo: {
    flex: 1,
  },
  invoiceNumberRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    marginBottom: 6,
  },
  invoiceNumber: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#007AFF',
  },
  autoTag: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    backgroundColor: '#F0F0F0',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  autoTagText: {
    fontSize: 10,
    fontWeight: '600' as const,
    color: '#666',
  },
  tenantName: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: '#1A1A1A',
    marginBottom: 4,
  },
  propertyInfo: {
    fontSize: 14,
    color: '#666',
  },
  invoiceAmount: {
    alignItems: 'flex-end' as const,
    gap: 4,
  },
  amount: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: '#34C759',
  },
  currency: {
    fontSize: 12,
    color: '#999',
    marginBottom: 4,
  },
  datesRow: {
    flexDirection: 'row' as const,
    gap: 16,
    marginBottom: 12,
  },
  dateItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
  },
  dateLabel: {
    fontSize: 12,
    color: '#666',
  },
  dateText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '600' as const,
  },
  invoiceActions: {
    flexDirection: 'row' as const,
    gap: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#F8F9FA',
    gap: 6,
  },
  actionText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#007AFF',
  },
  detailScroll: {
    maxHeight: 600,
  },
  detailHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'flex-start' as const,
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#007AFF',
  },
  detailHeaderLeft: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
  },
  detailInvoiceNumber: {
    fontSize: 24,
    fontWeight: '700' as const,
    color: '#1A1A1A',
  },
  detailHeaderRight: {
    alignItems: 'flex-end' as const,
  },
  detailAmount: {
    fontSize: 28,
    fontWeight: '700' as const,
    color: '#007AFF',
  },
  detailCurrency: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  detailSection: {
    marginBottom: 20,
  },
  detailSectionTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#007AFF',
    marginBottom: 8,
    textTransform: 'uppercase' as const,
  },
  detailSectionValue: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#1A1A1A',
    marginBottom: 4,
  },
  detailSectionSub: {
    fontSize: 14,
    color: '#666',
    marginBottom: 2,
  },
  detailDatesRow: {
    flexDirection: 'row' as const,
    gap: 20,
  },
  detailDateItem: {
    flex: 1,
  },
  detailDateLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
  },
  detailDateValue: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#1A1A1A',
  },
  lineItemRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  lineItemLeft: {
    flex: 1,
  },
  lineItemDescription: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#1A1A1A',
    marginBottom: 4,
  },
  lineItemDetails: {
    fontSize: 13,
    color: '#666',
  },
  lineItemAmount: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#1A1A1A',
  },
  detailTotals: {
    paddingTop: 12,
    borderTopWidth: 2,
    borderTopColor: '#E0E0E0',
    marginBottom: 20,
  },
  detailTotalRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    paddingVertical: 8,
  },
  detailTotalRowFinal: {
    borderTopWidth: 2,
    borderTopColor: '#E0E0E0',
    paddingTop: 12,
    marginTop: 8,
  },
  detailTotalLabel: {
    fontSize: 14,
    color: '#666',
  },
  detailTotalValue: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#1A1A1A',
  },
  detailTotalLabelFinal: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#1A1A1A',
  },
  detailTotalValueFinal: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: '#007AFF',
  },
  detailNotes: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    padding: 12,
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
  },
  detailActions: {
    gap: 12,
    marginTop: 12,
  },
  scheduledInfo: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    marginTop: 6,
  },
  scheduledText: {
    fontSize: 12,
    color: '#007AFF',
    fontWeight: '500' as const,
  },
});
