import { Invoice, InvoiceLineItem, Lease, TenantRenter, Property, Unit, PaymentCurrency } from '@/types';
import { getCurrencySymbol } from '@/constants/currencies';

export interface GenerateInvoiceParams {
  lease: Lease;
  tenantRenter: TenantRenter;
  property: Property;
  unit: Unit;
  invoiceDate: string;
  dueDate: string;
  currency: PaymentCurrency;
  invoiceNumber: string;
  includeLateFee?: boolean;
  lateFeeAmount?: number;
  additionalLineItems?: InvoiceLineItem[];
  notes?: string;
  autoGenerated?: boolean;
  recurringPeriod?: string;
}

export function generateInvoiceNumber(count: number): string {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const sequence = String(count + 1).padStart(4, '0');
  return `INV-${year}${month}-${sequence}`;
}

export function calculateLineItemTotal(lineItem: InvoiceLineItem): number {
  const baseAmount = lineItem.quantity * lineItem.unit_price;
  const taxAmount = lineItem.tax_rate ? (baseAmount * lineItem.tax_rate) / 100 : 0;
  return baseAmount + taxAmount;
}

export function generateInvoiceData(params: GenerateInvoiceParams): Omit<Invoice, 'id' | 'tenant_id' | 'created_at' | 'updated_at'> {
  const {
    lease,
    tenantRenter,
    property,
    unit,
    invoiceDate,
    dueDate,
    currency,
    invoiceNumber,
    includeLateFee = false,
    lateFeeAmount = 0,
    additionalLineItems = [],
    notes,
    autoGenerated = false,
    recurringPeriod,
  } = params;

  const lineItems: InvoiceLineItem[] = [
    {
      id: '1',
      description: `Rent for ${unit.unit_number}, ${property.name}`,
      quantity: 1,
      unit_price: lease.rent_amount,
      amount: lease.rent_amount,
    },
    ...additionalLineItems,
  ];

  if (includeLateFee && lateFeeAmount > 0) {
    lineItems.push({
      id: String(lineItems.length + 1),
      description: 'Late Payment Fee',
      quantity: 1,
      unit_price: lateFeeAmount,
      amount: lateFeeAmount,
    });
  }

  const subtotal = lineItems.reduce((sum, item) => sum + item.amount, 0);
  const taxAmount = lineItems.reduce((sum, item) => {
    const taxAmt = item.tax_rate ? (item.amount * item.tax_rate) / 100 : 0;
    return sum + taxAmt;
  }, 0);

  const totalAmount = subtotal + taxAmount;

  return {
    tenant_renter_id: tenantRenter.id,
    lease_id: lease.id,
    property_id: property.id,
    unit_id: unit.id,
    invoice_number: invoiceNumber,
    invoice_date: invoiceDate,
    due_date: dueDate,
    status: 'draft',
    currency,
    line_items: lineItems,
    subtotal,
    tax_amount: taxAmount > 0 ? taxAmount : undefined,
    late_fee_amount: includeLateFee ? lateFeeAmount : undefined,
    total_amount: totalAmount,
    balance_due: totalAmount,
    notes,
    auto_generated: autoGenerated,
    recurring_period: recurringPeriod,
  };
}

export function generateMonthlyInvoiceDate(lease: Lease): { invoiceDate: string; dueDate: string } {
  const today = new Date();
  const invoiceDate = today.toISOString().split('T')[0];
  
  const dueDay = lease.payment_due_day;
  const currentMonth = today.getMonth();
  const currentYear = today.getFullYear();
  
  let dueDateObj = new Date(currentYear, currentMonth, dueDay);
  
  if (dueDateObj < today) {
    dueDateObj = new Date(currentYear, currentMonth + 1, dueDay);
  }
  
  const dueDate = dueDateObj.toISOString().split('T')[0];
  
  return { invoiceDate, dueDate };
}

export function shouldGenerateInvoice(lease: Lease, existingInvoices: Invoice[]): boolean {
  if (lease.status !== 'active') {
    return false;
  }

  const today = new Date();
  const currentMonth = today.getMonth();
  const currentYear = today.getFullYear();

  const invoicesThisMonth = existingInvoices.filter((inv) => {
    const invDate = new Date(inv.invoice_date);
    return (
      inv.lease_id === lease.id &&
      invDate.getMonth() === currentMonth &&
      invDate.getFullYear() === currentYear &&
      inv.auto_generated
    );
  });

  return invoicesThisMonth.length === 0;
}

export function formatInvoiceHTML(
  invoice: Invoice,
  tenantRenter: TenantRenter,
  property: Property,
  unit: Unit,
  landlordInfo: { name: string; address?: string; email?: string; phone?: string }
): string {
  const currencySymbol = getCurrencySymbol(invoice.currency);
  const tenantName = tenantRenter.type === 'business' 
    ? tenantRenter.business_name 
    : `${tenantRenter.first_name} ${tenantRenter.last_name}`;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Invoice ${invoice.invoice_number}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; padding: 40px; background: #f5f5f5; }
    .invoice { max-width: 800px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    .header { display: flex; justify-content: space-between; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #007AFF; }
    .header h1 { color: #007AFF; font-size: 32px; }
    .header .invoice-number { color: #666; font-size: 14px; margin-top: 5px; }
    .details { display: flex; justify-content: space-between; margin-bottom: 40px; }
    .details-column { flex: 1; }
    .details-column h3 { font-size: 14px; color: #007AFF; margin-bottom: 10px; text-transform: uppercase; }
    .details-column p { font-size: 14px; color: #333; line-height: 1.6; }
    .table-container { margin-bottom: 40px; }
    table { width: 100%; border-collapse: collapse; }
    thead { background: #f8f9fa; }
    th { text-align: left; padding: 12px; font-size: 12px; color: #666; text-transform: uppercase; border-bottom: 2px solid #e0e0e0; }
    td { padding: 12px; font-size: 14px; color: #333; border-bottom: 1px solid #e0e0e0; }
    .text-right { text-align: right; }
    .totals { margin-left: auto; width: 300px; }
    .totals-row { display: flex; justify-content: space-between; padding: 8px 0; font-size: 14px; }
    .totals-row.total { font-size: 18px; font-weight: bold; padding-top: 12px; border-top: 2px solid #e0e0e0; margin-top: 8px; }
    .totals-row.total .amount { color: #007AFF; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; text-align: center; color: #666; font-size: 12px; }
    .notes { margin-top: 30px; padding: 15px; background: #f8f9fa; border-left: 3px solid #007AFF; }
    .notes h4 { font-size: 12px; color: #007AFF; margin-bottom: 8px; text-transform: uppercase; }
    .notes p { font-size: 14px; color: #666; line-height: 1.6; }
    .status-badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; text-transform: uppercase; }
    .status-draft { background: #f0f0f0; color: #666; }
    .status-sent { background: #e3f2fd; color: #007AFF; }
    .status-paid { background: #e8f5e9; color: #34C759; }
    .status-overdue { background: #ffebee; color: #FF3B30; }
  </style>
</head>
<body>
  <div class="invoice">
    <div class="header">
      <div>
        <h1>INVOICE</h1>
        <div class="invoice-number">#${invoice.invoice_number}</div>
        <div class="invoice-number">Date: ${new Date(invoice.invoice_date).toLocaleDateString()}</div>
      </div>
      <div style="text-align: right;">
        <span class="status-badge status-${invoice.status}">${invoice.status}</span>
      </div>
    </div>

    <div class="details">
      <div class="details-column">
        <h3>From</h3>
        <p>
          <strong>${landlordInfo.name}</strong><br/>
          ${landlordInfo.address || ''}<br/>
          ${landlordInfo.email || ''}<br/>
          ${landlordInfo.phone || ''}
        </p>
      </div>
      <div class="details-column">
        <h3>Bill To</h3>
        <p>
          <strong>${tenantName}</strong><br/>
          ${tenantRenter.address || ''}<br/>
          ${tenantRenter.email}<br/>
          ${tenantRenter.phone}
        </p>
      </div>
      <div class="details-column">
        <h3>Property Details</h3>
        <p>
          <strong>${property.name}</strong><br/>
          Unit: ${unit.unit_number}<br/>
          ${property.address}<br/>
          Due Date: ${new Date(invoice.due_date).toLocaleDateString()}
        </p>
      </div>
    </div>

    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th>Description</th>
            <th class="text-right">Qty</th>
            <th class="text-right">Unit Price</th>
            <th class="text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          ${invoice.line_items.map(item => `
            <tr>
              <td>${item.description}</td>
              <td class="text-right">${item.quantity}</td>
              <td class="text-right">${currencySymbol}${item.unit_price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
              <td class="text-right">${currencySymbol}${item.amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>

    <div class="totals">
      <div class="totals-row">
        <span>Subtotal:</span>
        <span>${currencySymbol}${invoice.subtotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
      </div>
      ${invoice.tax_amount ? `
        <div class="totals-row">
          <span>Tax:</span>
          <span>${currencySymbol}${invoice.tax_amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
        </div>
      ` : ''}
      ${invoice.late_fee_amount ? `
        <div class="totals-row" style="color: #FF9500;">
          <span>Late Fee:</span>
          <span>${currencySymbol}${invoice.late_fee_amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
        </div>
      ` : ''}
      ${invoice.discount_amount ? `
        <div class="totals-row" style="color: #34C759;">
          <span>Discount:</span>
          <span>-${currencySymbol}${invoice.discount_amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
        </div>
      ` : ''}
      <div class="totals-row total">
        <span>Total Amount:</span>
        <span class="amount">${currencySymbol}${invoice.total_amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${invoice.currency}</span>
      </div>
      ${invoice.amount_paid ? `
        <div class="totals-row">
          <span>Amount Paid:</span>
          <span>${currencySymbol}${invoice.amount_paid.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
        </div>
        <div class="totals-row total">
          <span>Balance Due:</span>
          <span class="amount">${currencySymbol}${(invoice.balance_due || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${invoice.currency}</span>
        </div>
      ` : ''}
    </div>

    ${invoice.notes ? `
      <div class="notes">
        <h4>Notes</h4>
        <p>${invoice.notes}</p>
      </div>
    ` : ''}

    <div class="footer">
      <p>Thank you for your business!</p>
      <p style="margin-top: 10px;">Please make payment by ${new Date(invoice.due_date).toLocaleDateString()}</p>
    </div>
  </div>
</body>
</html>
  `.trim();
}
