import { Payment, TenantRenter, Lease, Property, Unit, PaymentCurrency, Receipt } from '@/types';
import { getCurrencySymbol } from '@/constants/currencies';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';



export function generateReceiptNumber(count: number): string {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const sequence = String(count + 1).padStart(4, '0');
  return `RCPT-${year}${month}-${sequence}`;
}

export function generateReceiptData(
  payment: Payment,
  lease: Lease,
  receiptNumber: string,
  tenantId: string,
  autoGenerated: boolean = false
): Omit<Receipt, 'id' | 'generated_at' | 'created_at'> {
  return {
    tenant_id: tenantId,
    payment_id: payment.id,
    receipt_number: receiptNumber,
    receipt_date: payment.payment_date,
    tenant_renter_id: payment.tenant_renter_id,
    payment_amount: payment.amount + (payment.late_fee || 0),
    currency: payment.currency,
    payment_method: payment.payment_method,
    reference_number: payment.reference_number,
    lease_id: payment.lease_id,
    property_id: lease.property_id,
    unit_id: lease.unit_id,
    auto_generated: autoGenerated,
  };
}

export function formatReceiptHTML(
  receipt: Receipt,
  payment: Payment,
  tenantRenter: TenantRenter,
  lease: Lease,
  property: Property,
  unit: Unit,
  landlordInfo: { name: string; address?: string; email?: string; phone?: string }
): string {
  const currencySymbol = getCurrencySymbol(receipt.currency);
  const tenantName = tenantRenter.type === 'business' 
    ? tenantRenter.business_name 
    : `${tenantRenter.first_name} ${tenantRenter.last_name}`;

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-GB', { 
      day: 'numeric',
      month: 'long', 
      year: 'numeric' 
    });
  };

  const paymentMethodText = payment.payment_method 
    ? payment.payment_method.replace('_', ' ').toUpperCase()
    : 'NOT SPECIFIED';

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Receipt ${receipt.receipt_number}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; padding: 40px; background: #f5f5f5; }
    .receipt { max-width: 800px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); border: 2px solid #34C759; }
    .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 3px solid #34C759; }
    .header h1 { color: #34C759; font-size: 38px; margin-bottom: 8px; }
    .header .receipt-number { font-size: 18px; color: #666; font-weight: 600; }
    .receipt-date { text-align: center; font-size: 16px; color: #333; margin-bottom: 30px; }
    .amount-paid { text-align: center; background: #e8f5e9; padding: 20px; margin: 30px 0; border-radius: 8px; border: 2px solid #34C759; }
    .amount-paid .label { font-size: 14px; color: #666; margin-bottom: 8px; text-transform: uppercase; font-weight: 600; }
    .amount-paid .amount { font-size: 42px; color: #34C759; font-weight: 700; }
    .details { margin-bottom: 30px; }
    .details-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; margin-bottom: 30px; }
    .details-section { }
    .details-section h3 { font-size: 14px; color: #34C759; margin-bottom: 12px; text-transform: uppercase; font-weight: 700; }
    .details-section p { font-size: 14px; color: #333; line-height: 1.8; margin-bottom: 4px; }
    .details-section .strong { font-weight: 600; color: #1A1A1A; }
    .payment-info { background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
    .payment-info-row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #e0e0e0; }
    .payment-info-row:last-child { border-bottom: none; }
    .payment-info-row .label { font-size: 14px; color: #666; font-weight: 600; }
    .payment-info-row .value { font-size: 14px; color: #1A1A1A; font-weight: 600; }
    .breakdown { margin: 30px 0; }
    .breakdown-row { display: flex; justify-content: space-between; padding: 12px 0; font-size: 15px; border-bottom: 1px solid #e0e0e0; }
    .breakdown-row .label { color: #666; }
    .breakdown-row .value { color: #1A1A1A; font-weight: 600; }
    .breakdown-row.total { border-top: 3px solid #34C759; border-bottom: none; padding-top: 16px; margin-top: 12px; font-size: 20px; font-weight: 700; }
    .breakdown-row.total .label { color: #34C759; }
    .breakdown-row.total .value { color: #34C759; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 2px solid #e0e0e0; text-align: center; }
    .footer .stamp { background: #34C759; color: white; padding: 12px 24px; display: inline-block; border-radius: 6px; font-weight: 700; font-size: 16px; margin-bottom: 20px; }
    .footer p { font-size: 13px; color: #666; line-height: 1.6; }
    .footer .contact { margin-top: 20px; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <div class="receipt">
    <div class="header">
      <h1>PAYMENT RECEIPT</h1>
      <div class="receipt-number">${receipt.receipt_number}</div>
    </div>

    <div class="receipt-date">
      <strong>Receipt Date:</strong> ${formatDate(receipt.receipt_date)}
    </div>

    <div class="amount-paid">
      <div class="label">Amount Paid</div>
      <div class="amount">${currencySymbol}${receipt.payment_amount.toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${receipt.currency}</div>
    </div>

    <div class="details-grid">
      <div class="details-section">
        <h3>Received From</h3>
        <p class="strong">${tenantName}</p>
        <p>${tenantRenter.email}</p>
        <p>${tenantRenter.phone}</p>
        ${tenantRenter.address ? `<p>${tenantRenter.address}</p>` : ''}
      </div>
      <div class="details-section">
        <h3>Property Details</h3>
        <p class="strong">${property.name}</p>
        <p>Unit: ${unit.unit_number}</p>
        <p>${property.address}</p>
        ${property.city ? `<p>${property.city}, ${property.island}</p>` : ''}
      </div>
    </div>

    <div class="details-grid">
      <div class="details-section">
        <h3>Received By</h3>
        <p class="strong">${landlordInfo.name}</p>
        ${landlordInfo.address ? `<p>${landlordInfo.address}</p>` : ''}
        ${landlordInfo.email ? `<p>${landlordInfo.email}</p>` : ''}
        ${landlordInfo.phone ? `<p>${landlordInfo.phone}</p>` : ''}
      </div>
      <div class="details-section">
        <h3>Payment Information</h3>
        <p><strong>Payment Date:</strong> ${formatDate(payment.payment_date)}</p>
        <p><strong>Method:</strong> ${paymentMethodText}</p>
        ${payment.reference_number ? `<p><strong>Reference:</strong> ${payment.reference_number}</p>` : ''}
      </div>
    </div>

    <div class="breakdown">
      <div class="breakdown-row">
        <span class="label">Rent Amount:</span>
        <span class="value">${currencySymbol}${payment.amount.toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
      </div>
      ${payment.late_fee && payment.late_fee > 0 ? `
        <div class="breakdown-row">
          <span class="label">Late Fee:</span>
          <span class="value">${currencySymbol}${payment.late_fee.toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
        </div>
      ` : ''}
      <div class="breakdown-row total">
        <span class="label">Total Amount Paid:</span>
        <span class="value">${currencySymbol}${receipt.payment_amount.toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${receipt.currency}</span>
      </div>
    </div>

    ${payment.notes ? `
      <div class="payment-info">
        <div style="font-size: 14px; color: #34C759; font-weight: 700; margin-bottom: 8px; text-transform: uppercase;">Notes</div>
        <p style="font-size: 14px; color: #666; line-height: 1.6;">${payment.notes}</p>
      </div>
    ` : ''}

    <div class="footer">
      <div class="stamp">✓ PAID IN FULL</div>
      <p>This is an official receipt confirming payment received.</p>
      <p>Thank you for your payment!</p>
      <div class="contact">
        <p>For questions regarding this receipt, please contact ${landlordInfo.email || 'your property manager'}</p>
      </div>
    </div>
  </div>
</body>
</html>
  `.trim();
}

export async function generateReceiptPDF(
  receipt: Receipt,
  payment: Payment,
  tenantRenter: TenantRenter,
  lease: Lease,
  property: Property,
  unit: Unit,
  landlordInfo: { name: string; address?: string; email?: string; phone?: string }
): Promise<string> {
  const htmlContent = formatReceiptHTML(receipt, payment, tenantRenter, lease, property, unit, landlordInfo);
  
  try {
    const { uri } = await Print.printToFileAsync({
      html: htmlContent,
      base64: false,
    });
    
    console.log('[Receipt] Generated PDF at:', uri);
    return uri;
  } catch (error) {
    console.error('[Receipt] Error generating PDF:', error);
    throw error;
  }
}

export async function shareReceiptPDF(
  receipt: Receipt,
  payment: Payment,
  tenantRenter: TenantRenter,
  lease: Lease,
  property: Property,
  unit: Unit,
  landlordInfo: { name: string; address?: string; email?: string; phone?: string }
): Promise<void> {
  try {
    const pdfUri = await generateReceiptPDF(receipt, payment, tenantRenter, lease, property, unit, landlordInfo);
    
    const isAvailable = await Sharing.isAvailableAsync();
    if (isAvailable) {
      await Sharing.shareAsync(pdfUri, {
        mimeType: 'application/pdf',
        dialogTitle: `Share Receipt ${receipt.receipt_number}`,
        UTI: 'com.adobe.pdf',
      });
      console.log('[Receipt] PDF shared successfully');
    } else {
      console.warn('[Receipt] Sharing not available on this platform');
      throw new Error('Sharing not available on this platform');
    }
  } catch (error) {
    console.error('[Receipt] Error sharing PDF:', error);
    throw error;
  }
}
